### ISSUE TITLE
Not support in php v8.2

### ISSUE THREAD

**Issue by jeeinn** [HuasoFoundries/jpgraph#142]
Error:
### 1
```
 Using ${var} in strings is deprecated, use {$var} instead
```
* Can be fixed in this version

### 2
```
Function strftime() is deprecated
```
* Can be fixed in this version, Alternatives to this function `date()`

### 3
```
[TypeError]                              
  Unsupported operand types: int - string
Exception trace:
 () at /www/app/vendor/amenadiel/jpgraph/src/util/DateLocale.php:60
```
* Can be fixed in this version, using `(int)`

### 4
```
imagefilledpolygon(): Using the $num_points parameter is deprecated
#1 /www/app/vendor/amenadiel/jpgraph/src/image/Image.php(1611): imagefilledpolygon(Object(GdImage), Array, 4, 16777215)
```
* it cannot be modified directly, which will cause compatibility problems. (deprecated as of PHP 8.1.0)

### 5
```
Creation of dynamic property Amenadiel\JpGraph\Themes\UniversalTheme::$graph is deprecated
#0 /www/app/vendor/amenadiel/jpgraph/src/themes/Theme.php(52)
Creation of dynamic property Amenadiel\JpGraph\Graph\LinearTicks::$ticks_label is deprecated
#0 /www/app/vendor/amenadiel/jpgraph/src/graph/LinearTicks.php(209)
```
* Can be fixed in this version, declare the class properties

### 6
```
Implicit conversion from float 48.5 to int loses precision
#1 /www/app/vendor/amenadiel/jpgraph/src/image/Image.php(1158): imagettftext(Object(GdImage), 8, 0, 48.5, 98.0, 4473924
Implicit conversion from float 113.5 to int loses precision
#1 /www/app/vendor/amenadiel/jpgraph/src/image/Image.php(1048): imagettftext(Object(GdImage), 8, 0, 113.5, 52.0, 4473924, 
```
* Can be fixed in this version, using `(int)`

**Comment by logosur** [comment]
same issue here

**Comment by mmmsafry** [comment]
I am using php 8.3 I am getting the same 
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /opt/vhost/vendor/amenadiel/jpgraph/src/graph/Graph.php on line 895

is the any fix avilable in the vendor ?

**Comment by blacktek** [comment]
same issue with PHP 8.4.4
